apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: customer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-server:8888"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://discovery:8761/eureka"
        - name: SPRING_DATA_MONGODB_HOST
          value: "mongodb"
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: "customer"
        - name: SPRING_DATA_MONGODB_USERNAME
          value: "admin"
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: "admin"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 45
          periodSeconds: 10