apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: notification:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8040
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-server:8888"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://discovery:8761/eureka"
        - name: SPRING_DATA_MONGODB_HOST
          value: "mongodb"
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: "notification"
        - name: SPRING_DATA_MONGODB_USERNAME
          value: "admin"
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: "admin"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SPRING_MAIL_HOST
          value: "mail-dev"
        - name: SPRING_MAIL_PORT
          value: "1025"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8040
          initialDelaySeconds: 45
          periodSeconds: 10