apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: product:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8050
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-server:8888"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://discovery:8761/eureka"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgresql:5432/product"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "admin"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8050
          initialDelaySeconds: 45
          periodSeconds: 10