apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: microservices
spec:
  selector:
    app: config-server
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  type: ClusterIP