apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: microservices
spec:
  selector:
    app: notification
  ports:
  - port: 8040
    targetPort: 8040
    protocol: TCP
  type: ClusterIP