# Default configuration (Docker profile)
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

# Local Development Profile
---
spring:
  config:
    activate:
      on-profile: "local"
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Docker Profile
---
spring:
  config:
    activate:
      on-profile: "docker"
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

# Kubernetes Profile
---
spring:
  config:
    activate:
      on-profile: "k8s"
eureka:
  instance:
    hostname: discovery
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

# Production Profile
---
spring:
  config:
    activate:
      on-profile: "prod"
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:discovery}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:discovery}:8761/eureka

# Common Configuration for All Profiles
---
name:
  value: pandac
spring:
  cloud:
    config:
      override-system-properties: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: ${TRACING_PROBABILITY:1.0}
  metrics:
    export:
      prometheus:
        enabled: true
