# Common Configuration
---
server:
  port: 8050

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

# Local Development Profile
---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    show-sql: true

# Docker Profile
---
spring:
  config:
    activate:
      on-profile: "docker"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/product
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

# Kubernetes Profile
---
spring:
  config:
    activate:
      on-profile: "k8s"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/product
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5

# Production Profile
---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:postgresql}:${DB_PORT:5432}/${DB_NAME:product}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:20}
      minimum-idle: ${DB_POOL_MIN:5}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,flyway
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

